# Generated by Django 3.2 on 2021-04-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='content_image',
            field=models.ImageField(upload_to='editor/'),
        ),
    ]
